variable "cluster_name" {}
variable "task_family" {}
variable "task_cpu" {}
variable "task_memory" {}
variable "service_name" {}
variable "subnets" {}
variable "security_group_id" {}
variable "ecs_service_requests" {}
variable "ecs_service_payments" {}
variable "ecs_service_users" {}
//variable "ecs_service_products" {}